apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - otel/collector.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: zhanglab-platform-v17
      app.kubernetes.io/managed-by: kustomize
